### PR TITLE
re #52: Add ability to load transforms contained in ".seq.nrrd" files…

### LINKED ISSUE #52: Slicer crashes when importing .seq.mhd file
Hi Slicer community, 

I am having problems with importing sequence files (.seq.nrrd or .seq.mhd) that contain tracking data and ultrasound volumes acquired via PLUS. When trying to load a .seq.nrrd file as "Volume Sequence", only the volumes are imported into Slicer while the transforms are ignored. For importing .seq.mhd files as "Sequence Metafile", Slicer crashes instantly. 

Here are two examples for my sequence files:
.seq.nrrd format: https://www.dropbox.com/s/8ld1r30l0affqxc/4DUS-Sequence.zip?dl=0
.seq.mhd format: https://www.dropbox.com/s/32he9eb4w0rcm4r/4DUS-Sequence-MHD.zip?dl=0

Not sure if this is caused by an error in the PLUS file format or in the Slicer Sequences import function...?

Many thanks for your help!

### PR DESCRIPTION
**Pull request by Sunderlandkyl**
… and fix crash when metadata files contain images with 4 dimensions

Fixes #52

### CODE REVIEW

**Comment by Sunderlandkyl** [comment]
@lassoan I know we discussed not dealing with the crash right now, but I realized that the file is actually read for metadata before vtkMetaImageReader is used.

I added "NDims" to the list of metadata and performed the check to make sure that NDims is in the 1-3 range in vtkSlicerMetafileImporterLogic::ReadSequenceMetafile.

In retrospect, there's probably a better way to handle this.
Some possibilities might be:
- Adding another argument to vtkMRMLLinearTransformSequenceStorageNode::ReadSequenceMetafileTransforms that indicates if the  file is valid
- Returning an invalid value (-1?) -- Although the return type is supposed to represent the number of created nodes
- Opening the file again just to check for NDims

File: MetafileImporter/Logic/vtkSlicerMetafileImporterLogic.cxx [hunk 1]
```diff
@@ -421,6 +434,85 @@ vtkMRMLSequenceBrowserNode* vtkSlicerMetafileImporterLogic::ReadSequenceMetafile
...
+  }
+
+#ifdef ENABLE_PERFORMANCE_PROFILING
+  vtkNew<vtkTimerLog> timer;
+  timer->StartTimer();
+#endif
+
+  std::deque< vtkSmartPointer<vtkMRMLSequenceNode> > createdSequenceNodes;
+  std::map< std::string, std::string > imageMetaData;
+  vtkMRMLLinearTransformSequenceStorageNode::ReadSequenceMetafileTransforms(fileName, this->GetMRMLScene(), createdSequenceNodes,
```
Comment (lassoan) [inline MetafileImporter/Logic/vtkSlicerMetafileImporterLogic.cxx]: Rename to ReadSequenceFileTransforms

File: MetafileImporter/Logic/vtkSlicerMetafileImporterLogic.cxx [hunk 2]
```diff
@@ -421,6 +434,85 @@ vtkMRMLSequenceBrowserNode* vtkSlicerMetafileImporterLogic::ReadSequenceMetafile
...
+    frameNumberToIndexValueMap, imageMetaData, true);
```
Comment (lassoan) [inline MetafileImporter/Logic/vtkSlicerMetafileImporterLogic.cxx]: instead of a bool flag, use an enum like NRRD_SEQUENCE_FILE, METAIMAGE_SEQUENCE_FILE (it makes the code easier to read)

File: MetafileImporter/Logic/vtkSlicerMetafileImporterLogic.cxx [hunk 3]
```diff
@@ -421,6 +434,85 @@ vtkMRMLSequenceBrowserNode* vtkSlicerMetafileImporterLogic::ReadSequenceMetafile
   return sequenceBrowserNode.GetPointer();
 }
 
+//----------------------------------------------------------------------------
+vtkMRMLSequenceBrowserNode* vtkSlicerMetafileImporterLogic::ReadSequenceNRRD(const std::string& fileName, vtkCollection* addedSequenceNodes/*=NULL*/)
```
Comment (lassoan) [inline MetafileImporter/Logic/vtkSlicerMetafileImporterLogic.cxx]: This looks VERY similar to metaimage reading code. It would make this class shorter and easier to maintain if one method would handle both metaimage and nrrd file - similarly how you did it for ReadSequenceMetafileTransforms.

File: MetafileImporter/qSlicerMetafileReader.cxx [hunk 4]
```diff
@@ -86,7 +87,7 @@ qSlicerIO::IOFileType qSlicerMetafileReader::fileType() const
 //-----------------------------------------------------------------------------
 QStringList qSlicerMetafileReader::extensions() const
 {
-  return QStringList() << "Sequence Metafile (*.seq.mha *.seq.mhd *.mha *.mhd)";
+  return QStringList() << "Sequence Metafile (*.seq.mha *.seq.mhd *.mha *.mhd *.seq.nrrd *.nrrd)";
```
Comment (lassoan) [inline MetafileImporter/qSlicerMetafileReader.cxx]: seq.nrrd extension is already designated as volume sequence. If we add this file extension here then by default seq.nrrd files will be either offered to be loaded as volume sequence or as sequence metafile.

One solution could be to further complicate the extension, such as:
.plus.seq.nrrd
.igsio.seq.nrrd
.igs.seq.nrrd
.trk.seq.nrrd
...

Another option could be to specify a new composite file extension:
.igs.nrrd, .igs.mha
.igsio.nrrd, .igsio.mha
.trk.nrrd, .trk.mha
.plus.nrrd, .plus.mha

File: Sequences/MRML/vtkMRMLLinearTransformSequenceStorageNode.cxx [hunk 5]
```diff
@@ -87,7 +87,7 @@ void StringToInt(const char* strPtr, T &result)
 //----------------------------------------------------------------------------
 int vtkMRMLLinearTransformSequenceStorageNode::ReadSequenceMetafileTransforms(const std::string& fileName, vtkMRMLScene *scene,
   std::deque< vtkSmartPointer<vtkMRMLSequenceNode> > &createdNodes, std::map< int, std::string >& frameNumberToIndexValueMap,
-  std::map< std::string, std::string > &imageMetaData)
+  std::map< std::string, std::string > &imageMetaData, bool readFromNRRD/*=false*/)
```
Comment (lassoan) [inline Sequences/MRML/vtkMRMLLinearTransformSequenceStorageNode.cxx]: make it an enum

**Review by lassoan — COMMENTED** [review]
Thank you, you did a great job! See a few comments inline.

**Comment by Sunderlandkyl** [comment]
Ok, changes made!

File: MetafileImporter/qSlicerMetafileReader.cxx [hunk 6]
```diff
@@ -98,14 +102,29 @@ bool qSlicerMetafileReader::load(const IOProperties& properties)
...
-  
-  vtkNew<vtkCollection> loadedSequenceNodes;  
-  vtkMRMLSequenceBrowserNode* browserNode = d->MetafileImporterLogic->ReadSequenceMetafile(fileName.toStdString(), loadedSequenceNodes.GetPointer());
+
+  vtkNew<vtkCollection> loadedSequenceNodes;
+
+  QFileInfo fileInfo;
+  fileInfo.setFile(fileName);
+
+  QString extension = fileInfo.suffix();
```
Comment (lassoan) [inline MetafileImporter/qSlicerMetafileReader.cxx]: convert extension to lowercase to make sure the string comparison later will work for any case

File: MetafileImporter/qSlicerMetafileImporterModuleWidget.cxx [hunk 7]
```diff
@@ -93,9 +93,9 @@ void qSlicerMetafileImporterModuleWidget
 ::onImportButtonClicked()
 {
   Q_D( qSlicerMetafileImporterModuleWidget );
-  
+
   QString fileName = QFileDialog::getOpenFileName( this, tr("Open metafile"), "", tr("MHA Files (*.mha)") );
```
Comment (lassoan) [inline MetafileImporter/qSlicerMetafileImporterModuleWidget.cxx]: maybe add *.nrrd file here as well

File: MetafileImporter/qSlicerMetafileReader.cxx [hunk 8]
```diff
@@ -86,7 +90,7 @@ qSlicerIO::IOFileType qSlicerMetafileReader::fileType() const
 //-----------------------------------------------------------------------------
 QStringList qSlicerMetafileReader::extensions() const
 {
-  return QStringList() << "Sequence Metafile (*.seq.mha *.seq.mhd *.mha *.mhd)";
+  return QStringList() << "Sequence Metafile (*.seq.mha *.seq.mhd *.mha *.mhd *.igsio.mha *.igsio.nrrd)";
```
Comment (lassoan) [inline MetafileImporter/qSlicerMetafileReader.cxx]: .igsio.mha and .igsio.nrrd extensions may be a bit long and I feel including IO for a file is somewhat redundant. Maybe .igs.mha and .igs.nrrd extensions would be better?

@adamrankin @ungi What do you think? What composite extension would you prefer for tracked image sequences? .seq.nrrd and .seq.mha would not work in general, because this file extensions are used for simple (non-tracked) volume sequences.

**Review by lassoan — COMMENTED** [review]
Looks good, thank you. Just a few minor comments - see inline.

File: MetafileImporter/qSlicerMetafileReader.cxx (hunk 8 above)
Comment (ungi) [reply MetafileImporter/qSlicerMetafileReader.cxx]: igs.* seems like a good choice. Not too long, and I don't think anyone else wanted to reserve it.

Comment (Sunderlandkyl) [reply MetafileImporter/qSlicerMetafileReader.cxx]: I don't have much of a preference. I agree that igsio is quite long.
I've implemented the `*.igs.*` extension.

**Comment by Sunderlandkyl** [comment]
For some reason I thought that this had already been integrated. Are there any other changes or can I go ahead and integrate?

File: MetafileImporter/qSlicerMetafileReader.cxx [hunk 9]
```diff
@@ -86,7 +90,7 @@ qSlicerIO::IOFileType qSlicerMetafileReader::fileType() const
 //-----------------------------------------------------------------------------
 QStringList qSlicerMetafileReader::extensions() const
 {
-  return QStringList() << "Sequence Metafile (*.seq.mha *.seq.mhd *.mha *.mhd)";
+  return QStringList() << "Sequence Metafile (*.seq.mha *.seq.mhd *.mha *.mhd *.igs.mha *.igs.nrrd)";
```
Comment (lassoan) [inline MetafileImporter/qSlicerMetafileReader.cxx]: Please also add *.igs.mhd and *.igs.nhdr

File: Sequences/MRML/vtkMRMLLinearTransformSequenceStorageNode.cxx [hunk 10]
```diff
@@ -116,15 +116,44 @@ int vtkMRMLLinearTransformSequenceStorageNode::ReadSequenceMetafileTransforms(co
...
+    else
+    {
+      separatorFound = lineStr.find_first_of("=");
+    }
+
+    if (separatorFound == std::string::npos)
+    {
+      if (fileType == NRRD_SEQUENCE_FILE)
+      {
+        break;
```
Comment (lassoan) [inline Sequences/MRML/vtkMRMLLinearTransformSequenceStorageNode.cxx:142]: please add a comment what does this mean (error, end of header, …)

**Review by lassoan — APPROVED** [review]
Thank you, it looks good, I had just two trivial comments.
