### PR TITLE
BUG: Fix memory leaks after loading transform from sequence

### LINKED ISSUE #69: Memory leaks when loading Sequence Metafile with transforms
After loading a Sequence Metafile that has transform sequences, there are memory leaks upon closing Slicer. There are not any leaks when loading a Sequence Metafile that does not have any transform sequences.

It is something within this code section in `readSequenceFile`.
https://github.com/SlicerRt/Sequences/blob/e67d15ea8fcfc0914c547d8e338e30f7a155976a/MetafileImporter/Logic/vtkSlicerMetafileImporterLogic.cxx#L327-L332

Results in the following leaks. If there are 2 transform sequences in the file, then all instances are doubled.
```powershell

vtkDebugLeaks has   detected LEAKS!
--
Class "vtkMRMLFiducialListNode"   has 2 instances still around.
Class   "vtkSegmentationConverter" has 2 instances still around.
Class   "vtkMRMLColorTableStorageNode" has 2 instances still around.
Class   "vtkMRMLStreamingVolumeNode" has 2 instances still around.
Class   "vtkMRMLLabelMapVolumeDisplayNode" has 2 instances still around.
Class "vtkMRMLTableStorageNode"   has 2 instances still around.
Class "vtkMRMLPlotViewNode" has   2 instances still around.
Class "vtkCellData" has 4   instances still around.
Class   "vtkOrientedGridTransform" has 2 instances still around.
Class   "vtkTransformPolyDataFilter" has 2 instances still around.
Class "vtkCollection" has 8   instances still around.
Class   "vtkMRMLFreeSurferModelStorageNode" has 2 instances still around.
Class "vtkMRMLROIListNode" has   2 instances still around.
Class "vtkInformationVector"   has 542 instances still around.
Class   "vtkMRMLDiffusionTensorDisplayPropertiesNode" has 2 instances still   around.
Class "vtkPerspectiveTransform"   has 4 instances still around.
Class   "vtkClosedSurfaceToBinaryLabelmapConversionRule" has 2 instances   still around.
Class "vtkMRMLScalarVolumeNode"   has 2 instances still around.
Class "vtkMRMLColorNode" has 2   instances still around.
Class "vtkDataSetAttributes"   has 2 instances still around.
Class "vtkPointData" has 4   instances still around.
Class "vtkGeometryFilter" has 4   instances still around.
Class   "vtkCompositeDataPipeline" has 100 instances still around.
Class   "vtkMRMLDiffusionTensorVolumeNode" has 2 instances still around.
Class "vtkMatrix3x3" has 2   instances still around.
Class "vtkObservation" has 112   instances still around.
Class "vtkTrivialProducer" has   4 instances still around.
Class "vtkMRMLTableViewNode"   has 2 instances still around.
Class "vtkMatrix4x4" has 322   instances still around.
Class   "vtkMRMLLinearTransformNode" has 62 instances still around.
Class   "vtkMRMLSegmentationStorageNode" has 2 instances still around.
Class "vtkPassThrough" has 4   instances still around.
Class "vtkImageMapToColors" has   10 instances still around.
Class "vtkMRMLNodeReference"   has 2 instances still around.
Class "vtkSimpleTransform" has   74 instances still around.
Class   "vtkMRMLFreeSurferModelOverlayStorageNode" has 2 instances still   around.
Class "class vtkBuffer<unsigned   char>" has 2 instances still around.
Class   "vtkMRMLSegmentationDisplayNode" has 2 instances still around.
Class "vtkImageShiftScale" has   4 instances still around.
Class   "vtkColorTransferFunction" has 2 instances still around.
Class   "vtkMRMLTransformStorageNode" has 2 instances still around.
Class "vtkObserverManager" has   190 instances still around.
Class "vtkIntArray" has 296   instances still around.
Class "vtkPoints" has 4   instances still around.
Class   "vtkGridTransformConnectionHolder" has 2 instances still around.
Class "vtkInformation" has 1056   instances still around.
Class   "vtkMRMLLabelMapVolumeNode" has 2 instances still around.
Class   "vtkMRMLDiffusionTensorVolumeDisplayNode" has 2 instances still   around.
Class   "vtkMRMLProceduralColorStorageNode" has 2 instances still around.
Class   "vtkMRMLTransformDisplayNode" has 2 instances still around.
Class "vtkMRMLPlotChartNode"   has 2 instances still around.
Class   "vtkMRMLSliceCompositeNode" has 2 instances still around.
Class   "vtkMRMLVectorVolumeDisplayNode" has 2 instances still around.
Class "vtkMRMLTableNode" has 2   instances still around.
Class "vtkMultiThreader" has 84   instances still around.
Class "vtkMRMLSnapshotClipNode"   has 2 instances still around.
Class "vtkTable" has 2   instances still around.
Class   "vtkClosedSurfaceToFractionalLabelmapConversionRule" has 2   instances still around.
Class "vtkMRMLSelectionNode"   has 2 instances still around.
Class   "vtkInformationIntegerPointerValue" has 4 instances still around.
Class "vtkEventBroker" has 1   instance still around.
Class "vtkLookupTable" has 2   instances still around.
Class "class   vtkBuffer<int>" has 296 instances still around.
Class "vtkMRMLClipModelsNode"   has 2 instances still around.
Class "vtkMRMLROINode" has 2   instances still around.
Class "vtkMRMLSliceNode" has 2   instances still around.
Class "vtkMRMLDoubleArrayNode"   has 2 instances still around.
Class "vtkImageThreshold" has 8   instances still around.
Class   "vtkMRMLProceduralColorNode" has 2 instances still around.
Class "vtkMRMLNRRDStorageNode"   has 2 instances still around.
Class "vtkOpenGLCamera" has 2   instances still around.
Class "vtkMRMLHierarchyNode"   has 2 instances still around.
Class "vtkSegmentation" has 2   instances still around.
Class   "vtkMRMLDiffusionWeightedVolumeDisplayNode" has 2 instances still   around.
Class   "vtkMRMLFiducialListStorageNode" has 2 instances still around.
Class "vtkIdList" has 4   instances still around.
Class "vtkMRMLPlotSeriesNode"   has 2 instances still around.
Class   "vtkMRMLDoubleArrayStorageNode" has 2 instances still around.
Class "vtkDoubleArray" has 14   instances still around.
Class "vtkAlgorithmOutput" has   84 instances still around.
Class "vtkMRMLCrosshairNode"   has 2 instances still around.
Class "vtkImageCast" has 2   instances still around.
Class "vtkMRMLColorTableNode"   has 2 instances still around.
Class   "vtkMRMLSubjectHierarchyNode" has 2 instances still around.
Class "vtkMRMLModelNode" has 2   instances still around.
Class   "vtkInformationIntegerValue" has 996 instances still around.
Class "vtkDiffusionTensorGlyph"   has 4 instances still around.
Class   "vtkMRMLGridTransformNode" has 2 instances still around.
Class "vtkMRMLChartNode" has 2   instances still around.
Class "vtkTagTable" has 104   instances still around.
Class   "vtkDiffusionTensorMathematics" has 4 instances still around.
Class "vtkImageRGBToHSI" has 2   instances still around.
Class "vtkVertex" has 2   instances still around.
Class "vtkMRMLSegmentationNode"   has 2 instances still around.
Class   "vtkMRMLDiffusionWeightedVolumeNode" has 2 instances still around.
Class   "vtkMRMLDisplayableHierarchyNode" has 2 instances still around.
Class   "vtkBinaryLabelmapToClosedSurfaceConversionRule" has 2 instances   still around.
Class   "vtkMRMLScriptedModuleNode" has 2 instances still around.
Class "vtkImageData" has 4   instances still around.
Class   "vtkImageExtractComponents" has 20 instances still around.
Class   "vtkMRMLScalarVolumeDisplayNode" has 2 instances still around.
Class "vtkMRMLVectorVolumeNode"   has 2 instances still around.
Class   "vtkMRMLHierarchyStorageNode" has 2 instances still around.
Class "vtkStringArray" has 66   instances still around.
Class   "vtkInformationExecutivePortVectorValue" has 76 instances still   around.
Class   "vtkImageMapToWindowLevelColors" has 8 instances still around.
Class "vtkMRMLTransformNode"   has 2 instances still around.
Class "vtkTransform" has 72   instances still around.
Class "vtkMRMLModelStorageNode"   has 2 instances still around.
Class "vtkMRMLChartViewNode"   has 2 instances still around.
Class "vtkMRMLSequenceNode" has   2 instances still around.
Class "vtkImageMathematics" has   2 instances still around.
Class   "vtkMRMLModelHierarchyNode" has 2 instances still around.
Class "vtkVoxel" has 2   instances still around.
Class "vtkInformationIterator"   has 104 instances still around.
Class "vtkMRMLModelDisplayNode"   has 2 instances still around.
Class "vtkFieldData" has 6   instances still around.
Class   "vtkOrientedBSplineTransform" has 2 instances still around.
Class   "vtkMRMLBSplineTransformNode" has 2 instances still around.
Class "vtkMRMLInteractionNode"   has 2 instances still around.
Class "vtkAssignAttribute" has   4 instances still around.
Class "vtkVariantArray" has 2   instances still around.
Class "vtkSubjectHierarchyItem"   has 4 instances still around.
Class "class   vtkBuffer<double>" has 14 instances still around.
Class "vtkLineSource" has 2   instances still around.
Class "vtkMRMLCameraNode" has 2   instances still around.
Class "class vtkBuffer<unsigned   long>" has 132 instances still around.
Class   "vtkMRMLVolumeArchetypeStorageNode" has 2 instances still around.
Class "vtkSphereSource" has 2   instances still around.
Class "vtkUnsignedCharArray"   has 2 instances still around.
Class "vtkMRMLLayoutNode" has 2   instances still around.
Class   "vtkStreamingDemandDrivenPipeline" has 4 instances still around.
Class "vtkImageStencil" has 8   instances still around.
Class   "vtkMRMLDiffusionTensorVolumeSliceDisplayNode" has 2 instances   still around.
Class "vtkMRMLViewNode" has 2   instances still around.
Class   "vtkImageAppendComponents" has 8 instances still around.
Class   "vtkBSplineTransformConnectionHolder" has 2 instances still around.
Class "vtkTimerLog" has 1   instance still around.
Class "vtkUnsignedLongArray"   has 132 instances still around.
Class "vtkThreshold" has 4   instances still around.
Class "vtkMRMLScene" has 2   instances still around.
Class "vtkCommand or subclass"   has 508 instances still around.
Class   "vtkInformationExecutivePortValue" has 82 instances still around.
Class "vtkImageLogic" has 8   instances still around.
Class   "vtkFractionalLabelmapToClosedSurfaceConversionRule" has 2   instances still around.
```

### PR DESCRIPTION
**Pull request by jamesobutler**
This closes #69.

Let me know if this is the correct fix or suggestions for other methods here!

Now after loading a sequence metafile with transform sequences and then closing Slicer:
`vtkDebugLeaks has found no leaks.`

### CODE REVIEW

File: Sequences/MRML/vtkMRMLLinearTransformSequenceStorageNode.cxx [hunk 1]
```diff
@@ -283,6 +283,7 @@ int vtkMRMLLinearTransformSequenceStorageNode::ReadSequenceFileTransforms(const
         }
         numberOfCreatedNodes++;
         transformsSequenceNode = newTransformsSequenceNode;
+        newTransformsSequenceNode->Delete();
```
Comment (jcfr) [inline Sequences/MRML/vtkMRMLLinearTransformSequenceStorageNode.cxx]: An other approach would be to update line 267 to use:

```
vtkSmartPointer<vtkMRMLSequenceNode> newTransformsSequenceNode;
```

instead of 

```
vtkMRMLSequenceNode* transformsSequenceNode = NULL;
```.

And `newTransformsSequenceNode = vtkSmartPointer<vtkMRMLSequenceNode>::New();` at link 281

Comment (jamesobutler) [reply Sequences/MRML/vtkMRMLLinearTransformSequenceStorageNode.cxx]: Do you mean update line 271 to use?:
```
vtkSmartPointer<vtkMRMLSequenceNode> newTransformsSequenceNode;
```
Anyways it doesn't seem to be working for me

Comment (jcfr) [reply Sequences/MRML/vtkMRMLLinearTransformSequenceStorageNode.cxx]: Yes.

Two changes:

line 271: `vtkSmartPointer<vtkMRMLSequenceNode> newTransformsSequenceNode;`
line 281: `newTransformsSequenceNode = vtkSmartPointer<vtkMRMLSequenceNode>::New();`

Comment (jamesobutler) [reply Sequences/MRML/vtkMRMLLinearTransformSequenceStorageNode.cxx]: Got it working, thanks! Pushed update
